### PR TITLE
Feature/slider component

### PR DESCRIPTION
**Pull request by fabio-sv**
# Filter component

## To Note
- I apologize for no animation - couldn't get it right. Animations on thumbs doesn't seem to be possible.
- Works on Chrome and should work on Safari (untested)
- Works on MS Edge
- Does not work on IE Explorer
- Does not work correctly on Firefox
- There is a white line circling the left of the thumb when pulled to the right - this is because to get the left highlighted, I needed to some hacky shadow business because chrome - Nothing worked to get rid of it, not polygons, radii, extra shadows, inset shadows, background colors applied conditionally, nothing. Will put in the todo pile.

## Using it

```js
import { createSlider } from "./components/slider/slider.js";

const container = document.getElementById("insert-box");
const slider= createSlider("RPM", {  initialValue: 3000,  max: 6500,  step: 15 });

container.appendChild(slider);
```

## Output

Filter

## Multiple in a container

Filters

### CODE REVIEW

**Comment by PauloN1** [comment]
Hey Fabio, did you notice your PR has  conflicts?

**Comment by fabio-sv** [comment]
Hey Paulo, Will fix, thanks.

**Comment by WesselBBD** [comment]
Example
They move now!

**Comment by fabio-sv** [comment]
> Example They move now!

PLUG!

**Review by fabio-sv — COMMENTED** [review]
Apologies for size, linting applied all over the place

**Review by PauloN1 — APPROVED** [review]

**Pull request merged**
